'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navigation from './components/Navigation'
import { useState } from 'react';
import { NearlyContext } from './context/context';
import {  UserData } from './typings/typings'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({children}:{children: React.ReactNode}) {
  const [userData, setUserData] = useState<UserData>({
    name:"Test",
    email:"e@mail.com",
    location_id:6078,
    selectedArea: {
      city:"Beaver Dams (NY)",
      radius:10000,
      location_id:6078
    }
  });

  return (
    <html lang="en">
      <body className=''>
        <div className='max-w-lg mx-auto'>
          <NearlyContext.Provider value={{userData, setUserData}}>
            <Navigation />
            {children}
          </NearlyContext.Provider>
        </div>
      </body>
    </html>
  )
}
